// Default seed list — only used on first DB init
export const DEFAULT_TEAMS = [
  "AIB",
  "Avengers",
  "Blade Runners",
  "Bravehearts",
  "Bulls",
  "Chester Cheetahs",
  "Collegeville Super Kings",
  "Conquerors Cricket Club",
  "CSK Warriors",
  "D Khiladis",
  "D'Town 11",
  "Eagles",
  "Elite Eleven",
  "EV-Avengers",
  "Ex-town Hunters",
  "Falcons",
  "FIGHTERS-XI",
  "Gladiators",
  "Hit and Run",
  "Jaguars",
  "Jalsa CC",
  "Keystone Strikers",
  "KGF Warriors",
  "KOP Mustangs",
  "Lancers",
  "Lethal Lansdale",
  "Mavericks",
  "Masters Cricket Club",
  "Old Monks",
  "Philly Chargers",
  "Philly Mawale",
  "Philly Spartans",
  "Predictables",
  "Raptors",
  "Red Lions",
  "Rising Lions",
  "Roaring Lions",
  "Royal Cheetahs",
  "Sentinels",
  "Slammers",
  "Steel Balls",
  "Street Lions",
  "Stumperz",
  "Super Eagles",
  "Super Strikers",
  "Thunderbolts",
  "Titans",
  "Unpredictables",
  "Valley Forge XI",
  "Vikings",
  "Volcanoes",
  "Warriors",
  "Wayne Warriors",
  "Wildcats",
  "Wild Wolves",
  "Yoddhas",
];
